try {
  throw new Error('something wrong');
} catch (error) {
  console.log(error);
}